# Generated by Django 4.1.3 on 2022-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=None),
        ),
    ]
