# Generated by Django 4.1.3 on 2022-11-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_product_name_alter_product_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="slug",
            new_name="slug_product",
        ),
    ]
