# Generated by Django 4.1.3 on 2022-11-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_slug_product_slug_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="slug_product",
            new_name="slug",
        ),
    ]
