# Generated by Django 4.1.3 on 2022-11-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_slug_product_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="images",
        ),
    ]
