# Generated by Django 4.1.3 on 2022-11-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_images_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ImageField(default=False, upload_to="photos/products"),
        ),
    ]
