# Generated by Django 4.1.3 on 2022-11-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_product_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="images",
            new_name="product_images",
        ),
    ]
