# Generated by Django 4.1.3 on 2022-11-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_prpduct_variation_product"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
